[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
primaryColor = "#00b4d8"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#000000"
font = "sans serif"
